# -*- coding: utf-8 -*-
"""aula6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15iUcyH5R-JWfIuxC3lXwMDc19kc5sdIS
"""

# # **Exercício 1:** Escreva um programa que use a função `range()` para gerar os números pares de 2 a 20 e, em seguida, imprima cada número.

# for i in range(2,21):
#     print(i)


# # **Exercício 2:** Escreva um programa que use a função `range()` para gerar os múltiplos de 5 em 5 a 50 e, em seguida.

# for n in range(5,51,5):
#     print(n)

# # **Exercício 3:** Escreva um programa que use a função `type()` para verificar o tipo de uma variável.

# numero  =  10
# tipo = type(numero)
# print(tipo)



# # **Exercício 4:** Escreva um programa que use a função `print()` para imprimir uma mensagem de saudação personalizada, incluindo o nome do usuário.

# nome  = input('>>')
# saldacao = 'Olá como esta?'
# print(saldacao, nome)


# **Exercício 5:** Escreva um programa que use a função `range()`
# para gerar os números ímpares de 1 a 10 e,
#em seguida, calcule e imprima a média desses números.
#média?

# 1 Imprima uma mensagem de boas-vindas na tela.

print('ola, seja bem vindo(a)!')


# 2 Declare uma variável booleana verdadeiro
# com o valor True e imprima seu tipo

boleana  =  True
tipo = type(boleana)
print(tipo)


# 3 Imprima o resultado da multiplicação de
# dois números decimais de sua escolha


print(15.5 * 2.4)

# 4 Imprima o resultado da divisão de dois números inteiros
# de sua escolha.

n1 = 2
n2 = 3
print(n1/n2)

# 5 Imprima o resultado da subtração de dois números
# inteiros de sua escolha


n3 = 2
n4 = 3
print(n3-n4)

# 7 Imprima o resultado da multiplicação de dois
# números decimais de sua escolha

n5 = 2
n6 = 3
print(n5*n6)

# 8 Declare uma variável numero e atribua um número inteiro.
# Em seguida, # imprima o dobro desse número

n7 = 10
dobro = n7 ** 2
print(dobro)


# 9 Crie uma calculadora de soma com as ferramentas
# que vc já # conhece(Use apenas input, print e variavel)

numero1 = float(input('>>'))
numero2 = float(input('>>'))
soma  =  numero1 + numero2
print (f'soma:  {soma} ')



# 10 Crie um sistema de cadastro com as estruturas que vc já
# conhece(Use apenas input, print e variavel)

print('Formulário de cadastro: ')

nome =  input('>>')
cpf =  input('>>')
email =  input('>>')
endereco =  input('>>')

print(f'''
Dados do fiormulário, deseja enviar?
{nome}
{cpf}
{email}
{endereco}55
''')